apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restgeld-postgres-pvc
  labels:
    app: restgeld
    component: database
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
