---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: restgeld-secrets
spec:
  encryptedData:
    postgres-user: ""
    postgres-password: ""
  template:
    metadata:
      creationTimestamp: null
      name: restgeld-secrets
    type: Opaque
